[tool.poetry]
name = "sqlalchemy-js-authentication"
version = "0.1.0"
description = ""
authors = ["Giuseppe Di Bona <giusedb@gmail.com>"]
readme = "README.md"
packages = [{include = "jsalchemy_authentication"}]

[tool.poetry.dependencies]
python = "^3.11"
sqlalchemy = "^2.0.36"
bcrypt = "^4.2.1"
sqlalchemy-js-web-context = "^0.1"
redis = "^6.4.0"
fakeredis = "^2.31.3"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
pylint = "^3.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"



[tool.poetry.group.local.dependencies]
sqlalchemy-js-web-context = { path = "../../libs/context", develop = true }
