[project]
name = "sqlalchemy-js-authentication"
version = "0.1.0"
description = ""
authors = [{ name = "Giuseppe Di Bona", email = "giusedb@gmail.com" }]
requires-python = ">=3.11,<4"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "sqlalchemy>=2.0.36,<3",
    "bcrypt>=4.2.1,<5",
    "sqlalchemy-js-web-context>=0.1,<0.2",
    "redis>=6.4.0,<7",
    "fakeredis>=2.31.3,<3",
]

[dependency-groups]
dev = [
    "pytest>=8.3.3,<9",
    "pylint>=3.3.1,<4",
]
local = ["sqlalchemy-js-web-context"]

[tool.uv]
default-groups = [
    "dev",
    "local",
]

[tool.uv.sources]
sqlalchemy-js-web-context = { path = "../../libs/jsa-context", editable = true }

[tool.uv.build-backend]
module-name = ["jsalchemy_authentication"]
module-root = ""

[build-system]
requires = ["uv_build>=0.9.17,<0.10.0"]
build-backend = "uv_build"
